name: "Continuous Delivery"

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar el CLI de Google Cloud con credenciales de cuenta de servicio
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_KEY }}
          export_default_credentials: true

      # 3. Desplegar en Google Cloud Run
      - name: Deploy to Cloud Run
        run: |          
          gcloud run deploy flight-delay-predictor --source . --region $REGION --allow-unauthenticated